### ISSUE TITLE
How could I get the complete images on result 

### ISSUE THREAD

**Issue by Sun-wei-hao** [khdlr/HED-UNet#1]
Hello, Konrad Heidler
I'm trying to show the complete image on result ,
Can you give me some idea  on coding. Thanks a lot.

![101_1](https://user-images.githubusercontent.com/48707064/116980442-d0360480-acf8-11eb-8dda-97475628c9c9.jpg)

**Comment by khdlr** [comment]
Hi there! I'm not 100% sure I got your question right. Are you referring to the full output tiles as they are displayed in the README?

In order to achieve that, you need to cut the full tiles into smaller patches (choose the patch size according to your available GPU memory), predict each one of those patches, and then merge them again. Maybe this paper can give you a better idea of the process: https://arxiv.org/abs/1805.12219
